### ISSUE TITLE
Wavy and incorrect flow plot when I have ML

### ISSUE THREAD

**Issue by lapardhaja** [ucbtrans/opt#183]
![image](https://user-images.githubusercontent.com/60490284/95250618-33959d80-07cf-11eb-9ea9-e73045d4aeca.png)

**Comment by ggomes** [comment]
@sevilap29 This problem is fixed with the latest OTM. You will see another problem in section B->C, but it is related to the lane change model, something we will need to discuss more as a group. I suggest that if the wavy flow problem is fixed, to close this issue.

![image](https://user-images.githubusercontent.com/1287509/95925614-1e8cb180-0d6f-11eb-8557-f25baccd1c40.png)
