### ISSUE TITLE
Wrong flow on other off-ramps when one off-ramp demand exceeds its capacity

### ISSUE THREAD

**Issue by lapardhaja** [ucbtrans/opt#195]
If I have multiple off-ramps and on one off-ramp the demand of it exceeds it's capacity, the flow of the other off-ramps change even though it shouldn't. 

As you see here it is stuck at 750 for the entire simulation even though it should not.
![image](https://user-images.githubusercontent.com/60490284/96297349-904e4080-0fa5-11eb-8ac0-30f469746036.png)

Normally it should like like this one
![image](https://user-images.githubusercontent.com/60490284/96297443-b5db4a00-0fa5-11eb-90d4-d0692216653a.png)

**Comment by ggomes** [comment]
@akurzhan @sevilap29  I am not seeing this problem. Was it fixed?

**Comment by ggomes** [comment]
This result is actually what we expect according to our model. This is because both offramps flow out of the same lanegroup (the GP lanegroup). The offramp with 50% split ratio saturates first and creates congestion on the mainline. Because there are fewer vehicles going to the other offramp (20%), that offramp gets starved. The expected flow on that offramp is 1900 * 20/50 = 760, which is what we see.
