### ISSUE TITLE
Wrong flow on On-Ramp and Off-Ramp

### ISSUE THREAD

**Issue by lapardhaja** [ucbtrans/opt#214]
Despite having introduced policies for OR and Off Ramp and having set the % of each commodity, the flow from the report are not correct.

On the OR I am setting 900 veh to be LOV and 100 to be HOV, however the plot is different. I am having HOV veh on the GP lane. Is that expected? I think it would make sense for the HOVs to be on the HOV lane since the policy is implemented for them and they are much less than in the GP lane
![image](https://user-images.githubusercontent.com/60490284/97032312-77e6a480-1516-11eb-9fed-a6530ac7621c.png)
![image](https://user-images.githubusercontent.com/60490284/97032377-93ea4600-1516-11eb-8eac-651fd8ceab32.png)

On the off-ramp I am expecting 100 HOV on the HOV lane and the 900 LOVs on the GP lane. However despite I have a policy implemented I see LOVs on the HOV lane and the flows are split 500 - 500

![image](https://user-images.githubusercontent.com/60490284/97032539-d90e7800-1516-11eb-9af1-125e32a1b41c.png)

**Comment by ggomes** [comment]
Issue 1
_"I think it would make sense for the HOVs to be on the HOV lane since the policy is implemented for them and they are much less than in the GP lane"_
According to the policy, HOVs are "free" to be wherever they want. The onramp is in freeflow, so it is reasonable that some HOVs will be there. 

Issue 2
This is a somewhat unrealistic situation. You have an outer offramp with a restricted HOV lane. I think an offramp would only have an HOV restriction if it was fed by a ML (ie an inner offramp). My sense is that the simulation is correctly depicting what would happen in this situation. LOV vehicles from the GP lane would see two offramp lanes and use either. They would only exit the ML on the offramp once they realized they were on it, which is what happens in the simulation.
