### ISSUE TITLE
Simulation does not run

### ISSUE THREAD

**Issue by lapardhaja** [ucbtrans/opt#215]
Simulation does not run if I have a barrier with HOVs and I have an off-ramp where I have a certain demand of HOVs that should leave.
I know that this configuration does not make sense cause If I wanted them to leave there should be no barrier, but I was just curious to see what would happen.

**Comment by ggomes** [comment]
@sevilap29 
This is a good thing to check, because people will definitely do this. 
My suggestion is that we prohibit this configuration. ie there should not be a barrier if it will prevent vehicles from reaching their exit. 
I have added a check to OTM that will throw an exception when this arises. 
@akurzhan This is a runtime exception that is thrown by OTMTask.run_simualtion and is passed to you in AppMainController.attachSimDataToScenario. Please grab it and return to the user.
