### ISSUE TITLE
Simulation does not run if i have barrier and outer off-ramp

### ISSUE THREAD

**Issue by lapardhaja** [ucbtrans/opt#222]
The simulation does not run if I have outer off-ramp and hov barrier. Normally it should not run if it is inner off-ramp but not outer

**Comment by ggomes** [comment]
solved with 221

**Comment by ggomes** [comment]
Here the HOV vehicles in the ML are unable to get to the outer offramp.
There are two things we can do: a) throw an exception, b) these HOV vehicles miss their exit (and resample the split ratio in at the next offramp).  In case b) the resulting offramp flows will be lower than what is expected due to split ratios. 
It is easy to toggle OTM betwen these two options (first few lines of FluidLaneGroup.get_lc_probabilities). I've now deployed option b), so there should be no exception thown.
