### ISSUE TITLE
Change of flow in 10 min instead of 5min

### ISSUE THREAD

**Issue by lapardhaja** [ucbtrans/opt#272]
For example I am expecting from 1000 veh/hr to go to 2000 veh/hr and that will be achieved at 65 min( since the change is applied at 60 min) however I that I get 2000 veh/hr at min 70 instead of 65.

![image](https://user-images.githubusercontent.com/60490284/105746674-98970f80-5ef4-11eb-92be-e17bf7053fb2.png)

**Comment by ggomes** [comment]
The interpretation of the graph at time t is "the average flow over the 5 minute period ending at time t". So for example the flow at t=0 is 0 (it should actually be undefined) because there is no period prior to t=0. Whether this is intuitive is debatable. Maybe we should change it to "the average flow over the 5 minute period *starting* at time t". I will close this issue, but Servet if you feel strongly about it, then reopen it and we can discuss and change how it is plotted.
