### ISSUE TITLE
Barrier and off-ramp

### ISSUE THREAD

**Issue by lapardhaja** [ucbtrans/opt#277]
Adding a barrier at a segment where there is ML and there is outer off-ramp, made the flow on GP 0. This does not make sense

![image](https://user-images.githubusercontent.com/60490284/105750222-53c1a780-5ef9-11eb-9a79-1a1833f9e7c8.png)

**Comment by ggomes** [comment]
I think it makes sense. On A->B you have 250 vph in the ML and 750 vph in the GP. Then in B->C everyone is supposed to go to the offramp. The 750 in the GP lane change lanes into AUX, and so no one exits GP -- its exiting flow is 0. The 250 in the ML cannot reach the offramp due to the barrier. They miss their exit and proceed to C->D. Flow exiting the ML is 250.
