### ISSUE TITLE
No formation of queues at ramps even though

### ISSUE THREAD

**Issue by lapardhaja** [ucbtrans/opt#291]
I am making really congested conditions however I do not see queues on the on-ramps.

![image](https://user-images.githubusercontent.com/60490284/106184388-52d98180-6156-11eb-8804-88246a08c28c.png)

**Comment by ggomes** [comment]
The reason is that you have relatively less flow on the onramp than on the mainline. The mainline has 1500 vph/lane, the onramp has 1000 vph/lane. The way the node model happens to evolve in this situation is to stabilize onramp flow at 2000 vph, and mainline flow at 4000 vph, so the congestion shows up on the mainline. The reason for this is complicated. I'll try to put together a writeup with an explanation.
