### ISSUE TITLE
drop of speed at the beginning of the plot

### ISSUE THREAD

**Issue by lapardhaja** [ucbtrans/opt#305]
![image](https://user-images.githubusercontent.com/60490284/107441732-97680400-6aea-11eb-95b2-fc62ea0cbba1.png)

**Comment by ggomes** [comment]
The first point at t=0 defaults to freeflow speed, since flow and density are both 0.
The second point which appears as a dip. I am not sure why this happens, but it is probably related to the averaging formulas we use, and probably have to do with Jensen's inequality. 
I have shifted the values that get plotted to the left by one time step, so the initial speed is not shown.
