### ISSUE TITLE
Remove Lane event and congestion

### ISSUE THREAD

**Issue by lapardhaja** [ucbtrans/opt#316]
I have only mainline demand which is 6000.
Initially I have 3GP and 1 ML with total capacity of 8000
I have 2 segmenets A-B and B-C
From B-C I remove 1 lane at 1:00h, so it's capacity should be 6000
However I observe at A-B congestion despite the fact that demand=capacity

**Comment by ggomes** [comment]
In A-B the flow distributes evenly, so there are initially 4500 in GP and 1500 in ML. 
These 4500 are then crammed into 2 lanes in B-C, with a total of 4000 vph capacity. 
Congestion is created because the vehicles in the ML continue on the ML, and vehicles on the GP continue on the GP. The lane drop occurs in the GP lanes only.
